Repository soulaklabs/bitoduc.fr, pull requests merged in 2018-08, with the labels that each got.

#183 Ajout de "Modifier"
  traductions.json
Labels: ni pour ni contre bien au contraire

#156 Ajout Fraude au Président
  traductions.json
Labels: bonne question, mamène

#182 Ajout de crypto-néologismes
  traductions.json
Labels: attendons lundi d'abord, ne prenons pas de décision trop hâtive
